using Breakwater.Analyzers.Operations;
using Microsoft.CodeAnalysis;

namespace Breakwater.Analyzers.Rules;

/// <summary>
/// BW024: <c>DeleteData</c> (typically generated from removing or changing <c>HasData</c> seed
/// rows) deletes matching rows in production too, including rows a user has since edited.
/// </summary>
internal sealed class DeleteDataRule : IMigrationRule
{
    public DiagnosticDescriptor Descriptor { get; } = RuleDescriptors.Create(
        "BW024",
        "DeleteData removes rows that may have been edited since seeding",
        "DeleteData on '{0}' deletes matching rows in every database this migration runs against, including rows a user has since edited",
        "DeleteData is usually generated by removing or changing a HasData seed row. It deletes by key " +
        "in every environment the migration runs in, including production rows a user may have since " +
        "edited - the delete has no idea the row changed. Confirm this is really meant to run against " +
        "live data before shipping it.");

    public object[]? Check(MigrationOperation operation, MigrationContext context)
    {
        return operation.Kind == MigrationOperationKind.DeleteData ? new object[] { operation.QualifiedTable } : null;
    }
}
